# Generated by Django 4.2.28 on 2026-05-29 14:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.bestleist_aufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256),
                            "DOKFOLDERUUID" character varying(100)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_BestLeist_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.bestleist_aufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_administration_confirmation AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.bestleist_aufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_administration_confirmation
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AdministrationConfirmationTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_administration_confirmation",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.vertrpruef_aufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256),
                            "DOKFOLDERUUID" character varying(100)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_VertrPruef_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.vertrpruef_aufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_contract_review_task AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.vertrpruef_aufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_contract_review_task
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ContractReviewTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_contract_review_task",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.freigabeaedir_aufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256),
                            "DOKFOLDERUUID" character varying(100)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_FreigabeAEDir_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.freigabeaedir_aufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_medical_board_clearance AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.freigabeaedir_aufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_medical_board_clearance
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="MedicalBoardClearanceTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_medical_board_clearance",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.projkalk_aufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256),
                            "DOKFOLDERUUID" character varying(100)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_ProjKalk_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.projkalk_aufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_project_calculation_task AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.projkalk_aufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_project_calculation_task
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ProjectCalculationTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_project_calculation_task",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.projektmeldung (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "PROJEKTTYP" character varying(100),
                            "PROJEKTBEGINNGEPLANT" bigint,
                            "PROJEKTENDEGEPLANT" bigint,
                            "FORSCHUNGART" character varying(30),
                            "PROJEKTVERANTWORTLICHEEINHEIT_APIID" character varying(50),
                            "PL1ROLLE" character varying(250),
                            "SUBPROJEKTJANEIN" character(1),
                            "EIGENMITTELJANEIN" character(1),
                            "EIGENMITTEL2JANEIN" character(1),
                            "INVESTIGATORINITIATED" character(1),
                            "LEAN1A" character varying(2),
                            "LEAN3" character varying(2),
                            "KURZBEZEICHNUNG" character varying(30),
                            "MENTORID_APIID" character varying(50),
                            "PROJEKTLEITER2NAME_APIID" character varying(50),
                            "PROJEKTLEITER1ID_APIID" character varying(50),
                            "PROJEKTSUMMEGEPLANT" double precision,
                            "PROJEKTTITELDE" character varying(1024),
                            "KLINISCHEPHASE" character varying(30),
                            "STUDIENDESIGN2" character(1),
                            "MULTINATIONAL" character(1),
                            "SPONSORID" character varying(10),
                            "CROAPNAME" character varying(250),
                            "LEAN2" character varying(2),
                            "LEAN5" character varying(2),
                            "WIBI_101" integer,
                            "WIBI_102" integer,
                            "WIBI_103" integer,
                            "WIBI_104" integer,
                            "WIBI_105" integer,
                            "WIBI_106" integer,
                            "WIBI_107" integer,
                            "WIBI_201" integer,
                            "WIBI_202" integer,
                            "WIBI_203" integer,
                            "WIBI_204" integer,
                            "WIBI_205" integer,
                            "WIBI_206" integer,
                            "WIBI_207" integer,
                            "WIBI_208" integer,
                            "WIBI_209" integer,
                            "WIBI_210" integer,
                            "WIBI_211" integer,
                            "WIBI_301" integer,
                            "WIBI_302" integer,
                            "WIBI_303" integer,
                            "WIBI_304" integer,
                            "WIBI_305" integer,
                            "WIBI_401" integer,
                            "WIBI_402" integer,
                            "WIBI_403" integer,
                            "WIBI_404" integer,
                            "WIBI_405" integer,
                            "WIBI_501" integer,
                            "WIBI_502" integer,
                            "WIBI_503" integer,
                            "WIBI_504" integer,
                            "WIBI_505" integer,
                            "WIBI_506" integer,
                            "WIBI_507" integer,
                            "WIBI_508" integer,
                            "WIBI_509" integer,
                            "WIBI_601" integer,
                            "WIBI_602" integer,
                            "WIBI_603" integer,
                            "WIBI_604" integer,
                            "WIBI_605" integer,
                            "FORSCHUNGSFELDMULTI" text,
                            "BETEILIGUNGSKRITERIUM" text,
                            "STUDIENTYPMULTI" text,
                            "PROJEKTSTATUS" character varying(500),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_FINISHED_BY_USER_ID_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_DECISION_CODE" character varying,
                            "WFL_TASK_INFO" character varying(256),
                            "PROJEKTBEGINNEFFEKTIV" bigint,
                            "PROJEKTENDEEFFEKTIV" bigint,
                            "PROJEKTINNENAUFTRAGSNR" character varying(30),
                            "PROJEKTSUMMEEFFEKTIV" double precision,
                            "RECHTSGRUNDLAGE" character varying(100),
                            "EXTERNEPROJPARTNER" character varying(250),
                            "KURZFASSUNG_DE" character varying(100),
                            "KURZFASSUNG_EN" character varying(100),
                            "FORSCHUNGSPRMIENBERECHTIGT" character varying(50),
                            "FORSCHUNGSPRAEMIETEXT" character varying(250),
                            "OVERHEADSATZ" double precision
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_Projektmeldung'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.projektmeldung
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_project_report AS
                        SELECT ("PROJEKTNUMMER")::integer AS id,
                            "UUID" AS uuid,
                            "KURZBEZEICHNUNG" AS short,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            "PROJEKTTYP" AS type,
                            to_date(("PROJEKTBEGINNGEPLANT")::text, 'YYYYMMDD'::text) AS planned_start,
                            to_date(("PROJEKTENDEGEPLANT")::text, 'YYYYMMDD'::text) AS planned_end,
                            "FORSCHUNGART" AS research_type,
                            ("PROJEKTVERANTWORTLICHEEINHEIT_APIID")::integer AS organization_id,
                            (lower(("SUBPROJEKTJANEIN")::text) = 'y'::text) AS subproject,
                            (lower(("EIGENMITTELJANEIN")::text) = 'y'::text) AS internal_funds,
                            (lower(("INVESTIGATORINITIATED")::text) = 'y'::text) AS investigator_initiated,
                            ("PROJEKTLEITER1ID_APIID")::integer AS leader_id,
                            ("MENTORID_APIID")::integer AS mentor_id,
                            "PROJEKTSUMMEGEPLANT" AS planned_total,
                            public.hstore(ARRAY['de'::text], ARRAY[("PROJEKTTITELDE")::text]) AS title,
                            "KLINISCHEPHASE" AS clinical_phase,
                            "STUDIENDESIGN2" AS study_design,
                            (lower(("MULTINATIONAL")::text) = 'y'::text) AS multi_national,
                            ("SPONSORID")::integer AS sponsor_id,
                            regexp_split_to_array("FORSCHUNGSFELDMULTI", '\s*\|\s*'::text) AS research_fields,
                            "BETEILIGUNGSKRITERIUM" AS cooperation_criteria,
                            regexp_split_to_array("STUDIENTYPMULTI", '\s*\|\s*'::text) AS study_types,
                            "PROJEKTSTATUS" AS status,
                            ("WFL_FINISHED_BY_USER_ID_APIID")::integer AS workflow_finished_by_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            to_date(("PROJEKTBEGINNEFFEKTIV")::text, 'YYYYMMDD'::text) AS effective_start,
                            to_date(("PROJEKTENDEEFFEKTIV")::text, 'YYYYMMDD'::text) AS effective_end,
                            "PROJEKTINNENAUFTRAGSNR" AS internal_job_number,
                            "PROJEKTSUMMEEFFEKTIV" AS effective_total,
                            public.hstore(ARRAY['de'::text, 'en'::text], ARRAY[("KURZFASSUNG_DE")::text, ("KURZFASSUNG_EN")::text]) AS abstract
                        FROM elektra.projektmeldung
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_project_report
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ProjectReport",
                    fields=[
                        (
                            "id",
                            models.PositiveIntegerField(
                                primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("short", models.TextField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("type", models.TextField(null=True)),
                        ("planned_start", models.DateField(null=True)),
                        ("planned_end", models.DateField(null=True)),
                        ("research_type", models.TextField(null=True)),
                        ("subproject", models.BooleanField(null=True)),
                        ("internal_funds", models.BooleanField(null=True)),
                        ("investigator_initiated", models.BooleanField(null=True)),
                        ("planned_total", models.PositiveIntegerField(null=True)),
                        ("title", django.contrib.postgres.fields.hstore.HStoreField()),
                        ("clinical_phase", models.TextField(null=True)),
                        ("study_design", models.BooleanField(null=True)),
                        ("multi_national", models.BooleanField(null=True)),
                        (
                            "research_fields",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.TextField(null=True), size=None
                            ),
                        ),
                        ("cooperation_criteria", models.TextField(null=True)),
                        (
                            "study_types",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.TextField(null=True), size=None
                            ),
                        ),
                        ("status", models.TextField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("effective_start", models.DateField(null=True)),
                        ("effective_end", models.DateField(null=True)),
                        ("internal_job_number", models.TextField(null=True)),
                        ("effective_total", models.PositiveIntegerField(null=True)),
                        (
                            "abstract",
                            django.contrib.postgres.fields.hstore.HStoreField(),
                        ),
                    ],
                    options={
                        "db_table": "elektra_project_report",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.projektmeldungaufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_Projektmeldung_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.projektmeldungaufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_project_report_task AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.projektmeldungaufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_project_report_task
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ProjectReportTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_project_report_task",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.commitmentrekt_aufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256),
                            "DOKFOLDERUUID" character varying(100)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_CommitmentRekt_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.commitmentrekt_aufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_rectorate_commitment AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.commitmentrekt_aufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_rectorate_commitment
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="RectorateCommitmentTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_rectorate_commitment",
                        "managed": False,
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE FOREIGN TABLE elektra.freigabesponsor_aufgaben (
                            "UUID" character varying,
                            "PROJEKTNUMMER" character varying(10),
                            "PROJEKTADMINISTRATIONID_APIID" character varying(50),
                            "VERSION" character varying(15),
                            "CREATION_DATE" bigint,
                            "WFL_ACCEPTED_AT" bigint,
                            "WFL_ACCEPTED_BY_USER_APIID" character varying(50),
                            "WFL_CURRENT_WORKBASKET_APIID" character varying(50),
                            "WFL_FINISHED_AT" bigint,
                            "WFL_FINISHED_BY_USER_APIID" character varying(50),
                            "WFL_USER_INFO" character varying(1024),
                            "WFL_TASK_CODE" character varying(64),
                            "WFL_TASK_NAME" character varying(128),
                            "WFL_DECISION_CODE" character varying(256),
                            "DOKFOLDERUUID" character varying(100)
                        )
                        SERVER doxis
                        OPTIONS (
                            schema_name 'doxis-dev',
                            table_name 'ELEKTR.A_FreigabeSponsor_Aufgaben'
                        )
                    """,
                    reverse_sql="""
                        DROP FOREIGN TABLE elektra.freigabesponsor_aufgaben
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE MATERIALIZED VIEW public.elektra_sponsor_clearance_task AS
                        SELECT concat_ws('-'::text, "UUID", "VERSION") AS id,
                            "UUID" AS uuid,
                            ("PROJEKTNUMMER")::integer AS project_report_id,
                            ("PROJEKTADMINISTRATIONID_APIID")::integer AS administration_id,
                            "VERSION" AS version,
                            to_timestamp(("CREATION_DATE")::text, 'YYYYMMDDHH24MISSMS'::text) AS created,
                            to_timestamp(("WFL_ACCEPTED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_accepted,
                            ("WFL_ACCEPTED_BY_USER_APIID")::integer AS workflow_accepted_by_id,
                            ("WFL_CURRENT_WORKBASKET_APIID")::integer AS workflow_basket_id,
                            to_timestamp(("WFL_FINISHED_AT")::text, 'YYYYMMDDHH24MISSMS'::text) AS workflow_finished,
                            ("WFL_FINISHED_BY_USER_APIID")::integer AS workflow_finished_by_id,
                            "WFL_USER_INFO" AS workflow_user_info,
                            "WFL_TASK_CODE" AS workflow_task_code,
                            "WFL_TASK_NAME" AS workflow_task_name,
                            "WFL_DECISION_CODE" AS workflow_decision_code
                        FROM elektra.freigabesponsor_aufgaben
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW public.elektra_sponsor_clearance_task
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SponsorClearanceTask",
                    fields=[
                        (
                            "id",
                            models.CharField(
                                max_length=128, primary_key=True, serialize=False
                            ),
                        ),
                        ("uuid", models.UUIDField()),
                        ("version", models.PositiveIntegerField()),
                        ("created", models.DateTimeField()),
                        ("workflow_accepted", models.DateTimeField(null=True)),
                        ("workflow_finished", models.DateTimeField(null=True)),
                        ("workflow_user_info", models.TextField(null=True)),
                        ("workflow_task_code", models.TextField(null=True)),
                        ("workflow_task_name", models.TextField(null=True)),
                        ("workflow_decision_code", models.TextField(null=True)),
                    ],
                    options={
                        "db_table": "elektra_sponsor_clearance_task",
                        "managed": False,
                    },
                ),
            ],
        ),
    ]
