# Generated by Django 2.2.28 on 2024-12-05 14:28

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrationConfirmationTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_administration_confirmation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ContractReviewTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_contract_review_task",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalBoardClearanceTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_medica_board_clearance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectCalculationTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_project_calculation_task",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField()),
                ("short", models.TextField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("type", models.TextField(null=True)),
                ("planned_start", models.DateField(null=True)),
                ("planned_end", models.DateField(null=True)),
                ("research_Type", models.TextField(null=True)),
                ("subproject", models.BooleanField(null=True)),
                ("internal_funds", models.BooleanField(null=True)),
                ("investigator_initiated", models.BooleanField(null=True)),
                ("planned_total", models.PositiveIntegerField(null=True)),
                ("title", django.contrib.postgres.fields.hstore.HStoreField()),
                ("clinical_phase", models.TextField(null=True)),
                ("study_design", models.BooleanField(null=True)),
                ("multi_national", models.BooleanField(null=True)),
                ("sponsor", models.TextField(null=True)),
                ("research_field", models.TextField(null=True)),
                ("cooperation_criteria", models.TextField(null=True)),
                ("study_type", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("internal_job_number", models.TextField(null=True)),
                ("total_effective", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "elektra_project_report",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectReportTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_project_report_task",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RectorateCommitmentTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_rectorate_commitment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SponsorClearanceTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.PositiveIntegerField()),
                ("created", models.DateTimeField()),
                ("workflow_accepted", models.DateTimeField(null=True)),
                ("workflow_finished", models.DateTimeField(null=True)),
                ("workflow_user_info", models.TextField(null=True)),
                ("workflow_task_code", models.TextField(null=True)),
                ("workflow_task_name", models.TextField(null=True)),
                ("workflow_decision_code", models.TextField(null=True)),
            ],
            options={
                "db_table": "elektra_sponsor_clearance_task",
                "managed": False,
            },
        ),
    ]
