# Generated by Django 2.2.28 on 2024-12-05 14:28

from django.db import migrations

from ..conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE SCHEMA elektra;

            CREATE FOREIGN TABLE elektra.projektmeldung (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "PROJEKTTYP" varchar(100) NULL,
                "PROJEKTBEGINNGEPLANT" int8 NULL,
                "PROJEKTENDEGEPLANT" int8 NULL,
                "FORSCHUNGART" varchar(30) NULL,
                "PROJEKTVERANTWORTLICHEEINHEIT_APIID" varchar(50) NULL,
                "PL1ROLLE" varchar(250) NULL,
                "SUBPROJEKTJANEIN" bpchar(1) NULL,
                "EIGENMITTELJANEIN" bpchar(1) NULL,
                "EIGENMITTEL2JANEIN" bpchar(1) NULL,
                "INVESTIGATORINITIATED" bpchar(1) NULL,
                "LEAN1A" varchar(2) NULL,
                "LEAN3" varchar(2) NULL,
                "KURZBEZEICHNUNG" varchar(30) NULL,
                "MENTORID_APIID" varchar(50) NULL,
                "PROJEKTLEITER2NAME_APIID" varchar(50) NULL,
                "PROJEKTLEITER1ID_APIID" varchar(50) NULL,
                "PROJEKTSUMMEGEPLANT" float8 NULL,
                "PROJEKTTITELDE" varchar(100) NULL,
                "KLINISCHEPHASE" varchar(30) NULL,
                "STUDIENDESIGN2" bpchar(1) NULL,
                "MULTINATIONAL" bpchar(1) NULL,
                "SPONSORNAME" varchar(250) NULL,
                "CROAPNAME" varchar(250) NULL,
                "LEAN2" varchar(2) NULL,
                "LEAN5" varchar(2) NULL,
                "WIBI_101" int4 NULL,
                "WIBI_102" int4 NULL,
                "WIBI_103" int4 NULL,
                "WIBI_104" int4 NULL,
                "WIBI_105" int4 NULL,
                "WIBI_106" int4 NULL,
                "WIBI_107" int4 NULL,
                "WIBI_201" int4 NULL,
                "WIBI_202" int4 NULL,
                "WIBI_203" int4 NULL,
                "WIBI_204" int4 NULL,
                "WIBI_205" int4 NULL,
                "WIBI_206" int4 NULL,
                "WIBI_207" int4 NULL,
                "WIBI_208" int4 NULL,
                "WIBI_209" int4 NULL,
                "WIBI_210" int4 NULL,
                "WIBI_211" int4 NULL,
                "WIBI_301" int4 NULL,
                "WIBI_302" int4 NULL,
                "WIBI_303" int4 NULL,
                "WIBI_304" int4 NULL,
                "WIBI_305" int4 NULL,
                "WIBI_401" int4 NULL,
                "WIBI_402" int4 NULL,
                "WIBI_403" int4 NULL,
                "WIBI_404" int4 NULL,
                "WIBI_405" int4 NULL,
                "WIBI_501" int4 NULL,
                "WIBI_502" int4 NULL,
                "WIBI_503" int4 NULL,
                "WIBI_504" int4 NULL,
                "WIBI_505" int4 NULL,
                "WIBI_506" int4 NULL,
                "WIBI_507" int4 NULL,
                "WIBI_508" int4 NULL,
                "WIBI_509" int4 NULL,
                "WIBI_601" int4 NULL,
                "WIBI_602" int4 NULL,
                "WIBI_603" int4 NULL,
                "WIBI_604" int4 NULL,
                "WIBI_605" int4 NULL,
                "FORSCHUNGSFELDMULTI" text NULL,
                "BETEILIGUNGSKRITERIUM" text NULL,
                "STUDIENTYPMULTI" text NULL,
                "PROJEKTSTATUS" varchar(500) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_FINISHED_BY_USER_ID_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_DECISION_CODE" varchar NULL,
                "WFL_TASK_INFO" varchar(256) NULL,
                "PROJEKTBEGINNEFFEKTIV" int8 NULL,
                "PROJEKTENDEEFFEKTIV" int8 NULL,
                "PROJEKTINNENAUFTRAGSNR" varchar(30) NULL,
                "PROJEKTSUMMEEFFEKTIV" float8 NULL,
                "RECHTSGRUNDLAGE" varchar(100) NULL,
                "EXTERNEPROJPARTNER" varchar(250) NULL,
                "KURZFASSUNG_DE" varchar(100) NULL,
                "KURZFASSUNG_EN" varchar(100) NULL,
                "FORSCHUNGSPRMIENBERECHTIGT" varchar(50) NULL,
                "FORSCHUNGSPRAEMIETEXT" varchar(250) NULL,
                "OVERHEADSATZ" float8 NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_Projektmeldung');

            CREATE FOREIGN TABLE elektra.projektmeldungaufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_Projektmeldung_Aufgaben');

            CREATE FOREIGN TABLE elektra.bestleist_aufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL,
                "DOKFOLDERUUID" varchar(100) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_BestLeist_Aufgaben');

            CREATE FOREIGN TABLE elektra.commitmentrekt_aufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL,
                "DOKFOLDERUUID" varchar(100) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_CommitmentRekt_Aufgaben');

            CREATE FOREIGN TABLE elektra.freigabeaedir_aufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL,
                "DOKFOLDERUUID" varchar(100) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_FreigabeAEDir_Aufgaben');

            CREATE FOREIGN TABLE elektra.freigabesponsor_aufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL,
                "DOKFOLDERUUID" varchar(100) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_FreigabeSponsor_Aufgaben');

            CREATE FOREIGN TABLE elektra.projkalk_aufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL,
                "DOKFOLDERUUID" varchar(100) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_ProjKalk_Aufgaben');

            CREATE FOREIGN TABLE elektra.vertrpruef_aufgaben (
                "UUID" varchar,
                "PROJEKTNUMMER" varchar(10) NULL,
                "PROJEKTADMINISTRATIONID_APIID" varchar(50) NULL,
                "VERSION" varchar(15) NULL,
                "CREATION_DATE" int8 NULL,
                "WFL_ACCEPTED_AT" int8 NULL,
                "WFL_ACCEPTED_BY_USER_APIID" varchar(50) NULL,
                "WFL_CURRENT_WORKBASKET_APIID" varchar(50) NULL,
                "WFL_FINISHED_AT" int8 NULL,
                "WFL_FINISHED_BY_USER_APIID" varchar(50) NULL,
                "WFL_USER_INFO" varchar(1024) NULL,
                "WFL_TASK_CODE" varchar(64) NULL,
                "WFL_TASK_NAME" varchar(128) NULL,
                "WFL_DECISION_CODE" varchar(256) NULL,
                "DOKFOLDERUUID" varchar(100) NULL
            )
            SERVER doxis
            OPTIONS (schema_name '{schema}', table_name 'ELEKTR.A_VertrPruef_Aufgaben');

            CREATE MATERIALIZED VIEW public.elektra_project_report AS SELECT
                "PROJEKTNUMMER" AS id,
                "UUID" AS uuid,
                "KURZBEZEICHNUNG" AS short,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                "PROJEKTTYP" AS type,
                to_date("PROJEKTBEGINNGEPLANT"::text,'YYYYMMDD') AS planned_start,
                to_date("PROJEKTENDEGEPLANT"::text,'YYYYMMDD') AS planned_end,
                "FORSCHUNGART" AS research_type,
                "PROJEKTVERANTWORTLICHEEINHEIT_APIID"::integer AS organization_id,
                lower("SUBPROJEKTJANEIN") = 'y' AS subproject,
                lower("EIGENMITTELJANEIN") = 'y' AS internal_funds,
                lower("INVESTIGATORINITIATED") = 'y' AS investigator_initiated,
                "PROJEKTLEITER1ID_APIID"::integer AS leader_id,
                "MENTORID_APIID"::integer AS mentor_id,
                "PROJEKTSUMMEGEPLANT" AS planned_total,
                HSTORE(
                    ARRAY['de'],
                    ARRAY["PROJEKTTITELDE"]
                ) as title,
                "KLINISCHEPHASE" AS clinical_phase,
                "STUDIENDESIGN2" AS study_design,
                lower("MULTINATIONAL") = 'y' AS multi_national,
                "SPONSORNAME" AS sponsor,
                regexp_split_to_array("FORSCHUNGSFELDMULTI", '\s*\|\s*') AS research_fields,
                "BETEILIGUNGSKRITERIUM" AS cooperation_criteria,
                regexp_split_to_array("STUDIENTYPMULTI", '\s*\|\s*') AS study_types,
                "PROJEKTSTATUS" AS status,
                "WFL_FINISHED_BY_USER_ID_APIID"::integer AS workflow_finished_by_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                to_date("PROJEKTBEGINNEFFEKTIV"::text,'YYYYMMDD') AS effective_start,
                to_date("PROJEKTENDEEFFEKTIV"::text,'YYYYMMDD') AS effective_end,
                "PROJEKTINNENAUFTRAGSNR" AS internal_job_number,
                "PROJEKTSUMMEEFFEKTIV" AS effective_total,
                HSTORE(
                    ARRAY['de', 'en'],
                    ARRAY["KURZFASSUNG_DE", "KURZFASSUNG_EN"]
                ) as abstract
            FROM elektra.projektmeldung
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_project_report_task AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.projektmeldungaufgaben
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_project_calculation_task AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.projkalk_aufgaben
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_contract_review_task AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.vertrpruef_aufgaben
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_sponsor_clearance_task AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.freigabesponsor_aufgaben
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_administration_confirmation AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.bestleist_aufgaben
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_rectorate_commitment AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.commitmentrekt_aufgaben
            WITH DATA;

            CREATE MATERIALIZED VIEW public.elektra_medica_board_clearance AS SELECT
                concat_ws('-', "PROJEKTNUMMER", "VERSION") AS id,
                "UUID" AS uuid,
                "PROJEKTNUMMER" AS project_report_id,
                "PROJEKTADMINISTRATIONID_APIID"::integer AS administration_id,
                "VERSION" AS version,
                to_timestamp("CREATION_DATE"::text,'YYYYMMDDHH24MISSMS') AS created,
                to_timestamp("WFL_ACCEPTED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_accepted,
                "WFL_ACCEPTED_BY_USER_APIID"::integer AS workflow_accepted_by_id,
                "WFL_CURRENT_WORKBASKET_APIID"::integer AS workflow_basket_id,
                to_timestamp("WFL_FINISHED_AT"::text,'YYYYMMDDHH24MISSMS') AS workflow_finished,
                "WFL_FINISHED_BY_USER_APIID"::integer AS workflow_finished_by_id,
                "WFL_USER_INFO" AS workflow_user_info,
                "WFL_TASK_CODE" AS workflow_task_code,
                "WFL_TASK_NAME" AS workflow_task_name,
                "WFL_DECISION_CODE" AS workflow_decision_code
            FROM elektra.freigabeaedir_aufgaben
            WITH DATA;
            """.format(
                schema=settings.ELEKTRA_SCHEMA
            ),
            """
            DROP MATERIALIZED VIEW IF EXISTS public.elektra_medica_board_clearance;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_rectorate_commitment;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_administration_confirmation;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_sponsor_clearance_task;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_contract_review_task;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_project_calculation_task;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_project_report_task;

            DROP MATERIALIZED VIEW IF EXISTS public.elektra_project_report;

            DROP FOREIGN TABLE elektra.vertrpruef_aufgaben;

            DROP FOREIGN TABLE elektra.projkalk_aufgaben;

            DROP FOREIGN TABLE elektra.freigabesponsor_aufgaben;

            DROP FOREIGN TABLE elektra.freigabeaedir_aufgaben;

            DROP FOREIGN TABLE elektra.commitmentrekt_aufgaben;

            DROP FOREIGN TABLE elektra.bestleist_aufgaben;

            DROP FOREIGN TABLE elektra.projektmeldungaufgaben;

            DROP FOREIGN TABLE elektra.projektmeldung;

            DROP SCHEMA elektra;
            """,
        )
    ]
    dependencies = [
        ("elektra", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
